### PR TITLE
internal/gotemplate: format (gofmt) on Generate

### PR DESCRIPTION
**Pull request by codenoid**
This _make sure_ that generate Go files are formatted with [gofmt](https://pkg.go.dev/go/format#Source)

image 
I haven't look at the other files

### CODE REVIEW

**Comment by matthewmueller** [comment]
Thanks for the PR! Yes, I think we'll want to do this because the formatter is fast enough.

Mind adding a test or two?

**Comment by codenoid** [comment]
> Mind adding a test or two?

Done, we good to go?

**Comment by matthewmueller** [comment]
Yep, thanks for your contribution @codenoid!

**Comment by matthewmueller** [comment]
FYI. This is available in [v0.1.0](https://github.com/livebud/bud/releases/tag/v0.1.1). To upgrade, run:

```sh
curl -sf curl https://raw.githubusercontent.com/livebud/bud/main/install.sh | sh
```

**Pull request merged**
